$axure.loadCurrentPage({
  "url":"全部功能---个人中心资料管理.html",
  "generationDate":new Date(1499311308915.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"59288cb16d8a45b38fea910b37928f39",
    "type":"Axure:Page",
    "name":"全部功能---个人中心资料管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"90820221609c47d5a305e91de14c3351",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":140,
              "y":64},
            "size":{
              "width":1351,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ce38e2d57e41179d14162d6e50786c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":140,
                  "y":64},
                "size":{
                  "width":1351,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u0.png"}},
{
          "id":"2292b0a95989433ea4a2dcda5a01efcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1341,
              "y":79},
            "size":{
              "width":120,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3471f3c8d64d75a8bc08f768a24339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1341,
                  "y":79},
                "size":{
                  "width":120,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u2.png"}},
{
          "id":"faea1e08914341358612d8f98a0f9c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":181,
              "y":93},
            "size":{
              "width":181,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5462a528fc4bbb80dee5f4ef86fa6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":93},
                "size":{
                  "width":181,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18142f7b026a470d809683af94b3c529",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":395,
              "y":66},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6559def25bb14cd18e756070888700d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":395,
                  "y":66},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"6fdaa89423fa4d8ea77a47b6d61536be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":521,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa968033e14040d698460ae519fcb1f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":521,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"55401dbef79f49bd8dc2b9f68753873a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":646,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e034401bad6448d8fc71d6425e729ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":646,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u6.png"}},
{
          "id":"b16a1d5f9d184796b206cdee8ec93fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":772,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5208f9cf7964dc4a267f8807b17e2b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":772,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"0bb70fd90cea43c597808975b6317a52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":898,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29bcf57cddf48f49bf65f2a06dfa7e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":898,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"bfe9e788cc90469ea7c159dd9ed10ecc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":140,
              "y":138},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873544d53edc4f2ea7c0eb2bebc4a015",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":140,
                  "y":138},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"12bee254ac734f328f20342947fd4ae7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":694,
              "y":126},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f77f6db7b4054f5eb1245767be0e84b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":694,
                  "y":126},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"6fb5a0beac79425e97379dd14e12ec15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":423,
              "y":146},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8a8304b530348e4aee2f0ec8f326ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":423,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"36634497fe5241ac82aa264f41da26f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF931700},
            "location":{
              "x":540,
              "y":146},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa7a87bae504b5c8a4d228811c542cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF931700},
                "location":{
                  "x":540,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u18.png"}},
{
          "id":"46909ebba79c4c9a97d7dec574fda4e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":435,
              "y":298},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"681d52724576425a9a3ecd272806be18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":435,
                  "y":298},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u93.png"}},
{
          "id":"24d4c67fb2454f0fae90c72ef9ad91a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":332},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"fec9245ef1be482c85b35c6e32b8f888",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":435,
              "y":298},
            "size":{
              "width":375,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b16eb092b11c46be874128ff7b83c67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":435,
                  "y":298},
                "size":{
                  "width":375,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u97.png"}},
{
          "id":"8839932bf6c14cc8a218142820bc6243",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":440,
              "y":315},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc864bdabe474cb48e6a9a46fd8264b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":315},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40051b4b2fe3415489e97458425be5a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":586,
              "y":325},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60d7619204d04b689bef4bcf49a06e94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":586,
                  "y":325},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fed58df1fb94c8aaddb557ae08555c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":437,
              "y":301},
            "size":{
              "width":373,
              "height":12},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca8509690904976bb31b1e7dd298f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":437,
                  "y":301},
                "size":{
                  "width":373,
                  "height":12},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u103.png"}},
{
          "id":"100accce84ef490885b142d3dff5c111",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":450,
              "y":320},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1829e4dd1184c37bcd042cdcad7ac4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":320},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2ab5dc215745a891caa99540541256",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":444},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a511e1fbee3d47bfb880f196be91b5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":444},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09336e5fc61d4dbf82eed10a3c676491",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":494},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"05bd07c38b46419f9be6bd67ced6d0be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":520},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a118785ef034d78b55887396f99aa9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":520},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0343568a56184db399e8337380307f62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":381},
            "size":{
              "width":53,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09ac9e32f8847e6954a7b2ea2a6cc05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":381},
                "size":{
                  "width":53,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-全部功能-抽屉/u70.png"}},
{
          "id":"128a9d1d07214612877a6eeca6d487bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":584,
              "y":464},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084072ac777e45eeb8ab2a79eba78ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":584,
                  "y":464},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"918d44e7b875482d833c09de3e408588",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":460,
              "y":528},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc58df0301074eb69079dc8b6cbfa330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":528},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4901ac5d379a4cce837494ddc82ec5ba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":552},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全部功能---个人中心资料管理/u48_line.png"}},
{
          "id":"348be39c5f464c4a9103573c62106035",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":460,
              "y":572},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d445f418cde4a9ba4cb12ee03a42b11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":572},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00d8e88d2b624302965f831cfb4e1f04",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":596},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全部功能---个人中心资料管理/u48_line.png"}},
{
          "id":"cb35a74d8c06464fac8ee0e01a4b2ebc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":643},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全部功能---个人中心资料管理/u48_line.png"}},
{
          "id":"eee8832554cf4c2fa44c3b17dc8a3364",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":460,
              "y":616},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e278a570725f41cdba861683eb0e0412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":616},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642224c5f09e48bfa127eedecf363cfb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":690},
            "size":{
              "width":330,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/全部功能---个人中心资料管理/u48_line.png"}},
{
          "id":"f2f041411e894743839419000da9f051",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":460,
              "y":663},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b93eca70114f75bf4a198f03a2d24b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":663},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "90820221609c47d5a305e91de14c3351":{
      "scriptId":"u0"},
    "27ce38e2d57e41179d14162d6e50786c":{
      "scriptId":"u1"},
    "2292b0a95989433ea4a2dcda5a01efcb":{
      "scriptId":"u2"},
    "7c3471f3c8d64d75a8bc08f768a24339":{
      "scriptId":"u3"},
    "faea1e08914341358612d8f98a0f9c39":{
      "scriptId":"u4"},
    "0e5462a528fc4bbb80dee5f4ef86fa6a":{
      "scriptId":"u5"},
    "18142f7b026a470d809683af94b3c529":{
      "scriptId":"u6"},
    "6559def25bb14cd18e756070888700d3":{
      "scriptId":"u7"},
    "6fdaa89423fa4d8ea77a47b6d61536be":{
      "scriptId":"u8"},
    "fa968033e14040d698460ae519fcb1f3":{
      "scriptId":"u9"},
    "55401dbef79f49bd8dc2b9f68753873a":{
      "scriptId":"u10"},
    "8e034401bad6448d8fc71d6425e729ad":{
      "scriptId":"u11"},
    "b16a1d5f9d184796b206cdee8ec93fb5":{
      "scriptId":"u12"},
    "d5208f9cf7964dc4a267f8807b17e2b3":{
      "scriptId":"u13"},
    "0bb70fd90cea43c597808975b6317a52":{
      "scriptId":"u14"},
    "a29bcf57cddf48f49bf65f2a06dfa7e9":{
      "scriptId":"u15"},
    "bfe9e788cc90469ea7c159dd9ed10ecc":{
      "scriptId":"u16"},
    "873544d53edc4f2ea7c0eb2bebc4a015":{
      "scriptId":"u17"},
    "12bee254ac734f328f20342947fd4ae7":{
      "scriptId":"u18"},
    "f77f6db7b4054f5eb1245767be0e84b9":{
      "scriptId":"u19"},
    "6fb5a0beac79425e97379dd14e12ec15":{
      "scriptId":"u20"},
    "e8a8304b530348e4aee2f0ec8f326ba0":{
      "scriptId":"u21"},
    "36634497fe5241ac82aa264f41da26f0":{
      "scriptId":"u22"},
    "afa7a87bae504b5c8a4d228811c542cf":{
      "scriptId":"u23"},
    "46909ebba79c4c9a97d7dec574fda4e4":{
      "scriptId":"u24"},
    "681d52724576425a9a3ecd272806be18":{
      "scriptId":"u25"},
    "24d4c67fb2454f0fae90c72ef9ad91a8":{
      "scriptId":"u26"},
    "fec9245ef1be482c85b35c6e32b8f888":{
      "scriptId":"u27"},
    "b16eb092b11c46be874128ff7b83c67c":{
      "scriptId":"u28"},
    "8839932bf6c14cc8a218142820bc6243":{
      "scriptId":"u29"},
    "dc864bdabe474cb48e6a9a46fd8264b0":{
      "scriptId":"u30"},
    "40051b4b2fe3415489e97458425be5a6":{
      "scriptId":"u31"},
    "60d7619204d04b689bef4bcf49a06e94":{
      "scriptId":"u32"},
    "2fed58df1fb94c8aaddb557ae08555c7":{
      "scriptId":"u33"},
    "3ca8509690904976bb31b1e7dd298f62":{
      "scriptId":"u34"},
    "100accce84ef490885b142d3dff5c111":{
      "scriptId":"u35"},
    "c1829e4dd1184c37bcd042cdcad7ac4a":{
      "scriptId":"u36"},
    "1e2ab5dc215745a891caa99540541256":{
      "scriptId":"u37"},
    "a511e1fbee3d47bfb880f196be91b5f1":{
      "scriptId":"u38"},
    "09336e5fc61d4dbf82eed10a3c676491":{
      "scriptId":"u39"},
    "05bd07c38b46419f9be6bd67ced6d0be":{
      "scriptId":"u40"},
    "4a118785ef034d78b55887396f99aa9a":{
      "scriptId":"u41"},
    "0343568a56184db399e8337380307f62":{
      "scriptId":"u42"},
    "c09ac9e32f8847e6954a7b2ea2a6cc05":{
      "scriptId":"u43"},
    "128a9d1d07214612877a6eeca6d487bb":{
      "scriptId":"u44"},
    "084072ac777e45eeb8ab2a79eba78ffd":{
      "scriptId":"u45"},
    "918d44e7b875482d833c09de3e408588":{
      "scriptId":"u46"},
    "bc58df0301074eb69079dc8b6cbfa330":{
      "scriptId":"u47"},
    "4901ac5d379a4cce837494ddc82ec5ba":{
      "scriptId":"u48"},
    "348be39c5f464c4a9103573c62106035":{
      "scriptId":"u49"},
    "5d445f418cde4a9ba4cb12ee03a42b11":{
      "scriptId":"u50"},
    "00d8e88d2b624302965f831cfb4e1f04":{
      "scriptId":"u51"},
    "cb35a74d8c06464fac8ee0e01a4b2ebc":{
      "scriptId":"u52"},
    "eee8832554cf4c2fa44c3b17dc8a3364":{
      "scriptId":"u53"},
    "e278a570725f41cdba861683eb0e0412":{
      "scriptId":"u54"},
    "642224c5f09e48bfa127eedecf363cfb":{
      "scriptId":"u55"},
    "f2f041411e894743839419000da9f051":{
      "scriptId":"u56"},
    "09b93eca70114f75bf4a198f03a2d24b":{
      "scriptId":"u57"}}});