$axure.loadCurrentPage({
  "url":"修订历史.html",
  "generationDate":new Date(1499311303405.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6eb5a6bc3adb4b06ba99f9bd787c92ad",
    "type":"Axure:Page",
    "name":"修订历史",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8da2de4259d54feca06063a9739aa5b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":468,
              "y":144},
            "size":{
              "width":210,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"361820614ebc4c04afd1912dbe38b544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "location":{
                  "x":468,
                  "y":144},
                "size":{
                  "width":210,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c271526f7994794b43c26af016e9645",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":226},
            "size":{
              "width":960,
              "height":244}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13d3783ec0ae40708152f17920bbd85c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "size":{
                  "width":159,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6db58662064b4c5fbde337a669da6e8b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "size":{
                      "width":159,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u3.png"}},
{
              "id":"97651b2fbe2c48a6aab10fe1f289c0fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd8983403c96450997f3f474601800c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u9.png"}},
{
              "id":"1b8c5dad9d2f4af7a57019844334c222",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c202a17e2b7b4b0eb7f443b6e5eede89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u15.png"}},
{
              "id":"3704b438a9374d2799f1afe92e27033c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":159,
                  "y":0},
                "size":{
                  "width":623,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba34d1adde07446d9356ab0740605337",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "location":{
                      "x":159,
                      "y":0},
                    "size":{
                      "width":623,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u5.png"}},
{
              "id":"a9a3020551c0465ea499e1d6f207b622",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":159,
                  "y":34},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9911dcd0aefc40f1b2ffcc8c021e5c3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontWeight":"200",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":159,
                      "y":34},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u11.png"}},
{
              "id":"97f702d9f066440098a5c0567f21c35e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":159,
                  "y":64},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e1cd7b6b8f945d5b91f897a36175499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontWeight":"200",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":159,
                      "y":64},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u17.png"}},
{
              "id":"03060c470b3d437e84c0a0e3dccf7563",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF333333},
                "location":{
                  "x":782,
                  "y":0},
                "size":{
                  "width":178,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d4e85ea99ad44f89f13684573eb9354",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Regular', 'Heiti SC'",
                    "fontWeight":"200",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF333333},
                    "location":{
                      "x":782,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":34},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u7.png"}},
{
              "id":"aff19950e4b14339932ef6ee58815cea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":782,
                  "y":34},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45b3e2409b9f4b12b8b044aced4877e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":782,
                      "y":34},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u13.png"}},
{
              "id":"295a1ee6beed47c88b1d7ac2c187665a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":782,
                  "y":64},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"734bcb1e2b384beab438cfb11adb58f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":782,
                      "y":64},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u19.png"}},
{
              "id":"d6e2d12253634fce82405a2b8d4ac5dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":214},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39ea5cc0570c418a9e7c85ca02e988c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":214},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u45.png"}},
{
              "id":"71263e01155d490ab5d653d50b1b7e60",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":159,
                  "y":214},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9dd47f6d4a1468e81b52a8e4870fea2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":159,
                      "y":214},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u47.png"}},
{
              "id":"ccb36435cf17475795e615d8d5f89e2b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":782,
                  "y":214},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63f05325f53e478087f3b367baad57e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":782,
                      "y":214},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u49.png"}},
{
              "id":"cec4c805f2ff42fdae019a8c09174618",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a4d85517b1a490fadd32d2fd3ad7003",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u9.png"}},
{
              "id":"842918765f1c4f69a9368ed901c1958f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":159,
                  "y":94},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72b27cc074f449b5955df2ca8e5148ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":159,
                      "y":94},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u11.png"}},
{
              "id":"f192e952b90f4a3d8f6edff71b8a9202",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":782,
                  "y":94},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e251c2f66a9147baafbe78444d65cf69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":782,
                      "y":94},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u13.png"}},
{
              "id":"ce862cb7a6544ff4bcd1db0cb2db2a9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":184},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e8ed8c3e2b4463f8162f3fc9e0d9f15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":184},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u15.png"}},
{
              "id":"04620a106fa946df9e8c9b7b92737199",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":159,
                  "y":184},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55ae80b4bca74548bc3e51a1adadb14d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":159,
                      "y":184},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u17.png"}},
{
              "id":"92f9517cbecf45baa0b8626d0da52491",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":782,
                  "y":184},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"291a3c16004e40ff99c0d1639e304bab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":782,
                      "y":184},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u19.png"}},
{
              "id":"a9005bafb54b4f408a76faa274d1bfdb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4fb7f086ae54d079941a9b7d713b5ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u15.png"}},
{
              "id":"3206ed69bbce47a8ace0e17890b18739",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":159,
                  "y":124},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ef91017f41d43fca69f0066cd412854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":159,
                      "y":124},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u17.png"}},
{
              "id":"6d4b463c896f48f798c65fd2fbc1bedd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":782,
                  "y":124},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e501520f407945cbbdcbbea1392ccd97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":782,
                      "y":124},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u19.png"}},
{
              "id":"79e549f710f445b7a438e2f8d15e5621",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":0,
                  "y":154},
                "size":{
                  "width":159,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a3f34f0e8344a4c828a1a007f26c3d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":154},
                    "size":{
                      "width":159,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u9.png"}},
{
              "id":"183b5a0861f441ecbbf5d2d47ee3a98a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":159,
                  "y":154},
                "size":{
                  "width":623,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b8bc4e070af462fa4f6fe8c9569dc64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":159,
                      "y":154},
                    "size":{
                      "width":623,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u11.png"}},
{
              "id":"bb398202d94043b880b2cf8d65d04412",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":782,
                  "y":154},
                "size":{
                  "width":178,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd3393fd5eaf47afa70cf007b71c8b63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":782,
                      "y":154},
                    "size":{
                      "width":178,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修订历史/u13.png"}}]},
{
          "id":"6e4b0874521f42429d1154291d7140a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":-1,
              "y":-2},
            "size":{
              "width":1351,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3d23bc13d64786ac07823a55cdf9b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":-1,
                  "y":-2},
                "size":{
                  "width":1351,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u0.png"}},
{
          "id":"4bd5629e50d04b24b1f8b8cca067a282",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1200,
              "y":13},
            "size":{
              "width":120,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff0dbd5ef35486c966174965c7419fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1200,
                  "y":13},
                "size":{
                  "width":120,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u2.png"}},
{
          "id":"29cee2be13f44a14a15f535be762463f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":40,
              "y":27},
            "size":{
              "width":150,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae57c748f9840f2be6f488abb54926b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":27},
                "size":{
                  "width":150,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cebeb8ce3db470aa0fe6270a8b9059c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":254,
              "y":0},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67df0752c014481282558e5e5e817cec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":254,
                  "y":0},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u6.png"}},
{
          "id":"547c95411e0543f8a37719c693e99b9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":380,
              "y":-1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce85d7f5f1b46ffaf67d9e7deea6cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":380,
                  "y":-1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"f1ac059bce00413780ad08c1e65d401a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":505,
              "y":-1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dce20f96cb2449dda35ca5e6bb73aed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":505,
                  "y":-1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"6d700518e1fa4023b1069d29e74db2f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":631,
              "y":-1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5040602a3444669b5d94b88a7d217f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":631,
                  "y":-1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"505354b157ab43a99ff3369e0aa50bb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":757,
              "y":-1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"843ae8f6057d478995d9fd0f173567e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":757,
                  "y":-1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"a0eeeefd72e849538a16b15ab4affd06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":-1,
              "y":74},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20fbe3b063f4649b8852de79a579a14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":-1,
                  "y":74},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"d81364e882c74670af54c6272ee9d37d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":296,
              "y":62},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c781b63382644ed947e72ceceefdca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":296,
                  "y":62},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"9e721779a32d4055b5b11ab9a71729b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":-1,
              "y":74},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41668c9797504b4dbfc82f621b86e1b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":-1,
                  "y":74},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"c6f19ccacc884e38af7bb53b2c29e4f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":296,
              "y":62},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00ee52c140b4e07b0288228b41c6226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":296,
                  "y":62},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"c0f54691cf8f498f8abe1143d5ed668b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":270,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"577edd15e9934d09ae9323dfb31d2eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":270,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"1dda4222800c41b79e6b54b56d3efd11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":399,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfb33b783c1f42718d608e55ae1cdc09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":399,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"bb952035d07942f78a12e23456045da6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":510,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307863558b85437ebb0aa3c140b06e72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":510,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"bcaece7dc2cf4461b46a883da6444fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":614,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f924cfeaba49eda1e76c76b61c5db0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":614,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"e8a1cdb76b3e4b369209fbea21aef3b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF931700},
            "location":{
              "x":725,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c83360973946ea9de0c25eae4acb86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF931700},
                "location":{
                  "x":725,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8da2de4259d54feca06063a9739aa5b1":{
      "scriptId":"u0"},
    "361820614ebc4c04afd1912dbe38b544":{
      "scriptId":"u1"},
    "1c271526f7994794b43c26af016e9645":{
      "scriptId":"u2"},
    "13d3783ec0ae40708152f17920bbd85c":{
      "scriptId":"u3"},
    "6db58662064b4c5fbde337a669da6e8b":{
      "scriptId":"u4"},
    "3704b438a9374d2799f1afe92e27033c":{
      "scriptId":"u5"},
    "ba34d1adde07446d9356ab0740605337":{
      "scriptId":"u6"},
    "03060c470b3d437e84c0a0e3dccf7563":{
      "scriptId":"u7"},
    "7d4e85ea99ad44f89f13684573eb9354":{
      "scriptId":"u8"},
    "97651b2fbe2c48a6aab10fe1f289c0fa":{
      "scriptId":"u9"},
    "cd8983403c96450997f3f474601800c3":{
      "scriptId":"u10"},
    "a9a3020551c0465ea499e1d6f207b622":{
      "scriptId":"u11"},
    "9911dcd0aefc40f1b2ffcc8c021e5c3e":{
      "scriptId":"u12"},
    "aff19950e4b14339932ef6ee58815cea":{
      "scriptId":"u13"},
    "45b3e2409b9f4b12b8b044aced4877e0":{
      "scriptId":"u14"},
    "1b8c5dad9d2f4af7a57019844334c222":{
      "scriptId":"u15"},
    "c202a17e2b7b4b0eb7f443b6e5eede89":{
      "scriptId":"u16"},
    "97f702d9f066440098a5c0567f21c35e":{
      "scriptId":"u17"},
    "9e1cd7b6b8f945d5b91f897a36175499":{
      "scriptId":"u18"},
    "295a1ee6beed47c88b1d7ac2c187665a":{
      "scriptId":"u19"},
    "734bcb1e2b384beab438cfb11adb58f6":{
      "scriptId":"u20"},
    "cec4c805f2ff42fdae019a8c09174618":{
      "scriptId":"u21"},
    "5a4d85517b1a490fadd32d2fd3ad7003":{
      "scriptId":"u22"},
    "842918765f1c4f69a9368ed901c1958f":{
      "scriptId":"u23"},
    "72b27cc074f449b5955df2ca8e5148ce":{
      "scriptId":"u24"},
    "f192e952b90f4a3d8f6edff71b8a9202":{
      "scriptId":"u25"},
    "e251c2f66a9147baafbe78444d65cf69":{
      "scriptId":"u26"},
    "a9005bafb54b4f408a76faa274d1bfdb":{
      "scriptId":"u27"},
    "b4fb7f086ae54d079941a9b7d713b5ee":{
      "scriptId":"u28"},
    "3206ed69bbce47a8ace0e17890b18739":{
      "scriptId":"u29"},
    "4ef91017f41d43fca69f0066cd412854":{
      "scriptId":"u30"},
    "6d4b463c896f48f798c65fd2fbc1bedd":{
      "scriptId":"u31"},
    "e501520f407945cbbdcbbea1392ccd97":{
      "scriptId":"u32"},
    "79e549f710f445b7a438e2f8d15e5621":{
      "scriptId":"u33"},
    "5a3f34f0e8344a4c828a1a007f26c3d9":{
      "scriptId":"u34"},
    "183b5a0861f441ecbbf5d2d47ee3a98a":{
      "scriptId":"u35"},
    "8b8bc4e070af462fa4f6fe8c9569dc64":{
      "scriptId":"u36"},
    "bb398202d94043b880b2cf8d65d04412":{
      "scriptId":"u37"},
    "dd3393fd5eaf47afa70cf007b71c8b63":{
      "scriptId":"u38"},
    "ce862cb7a6544ff4bcd1db0cb2db2a9f":{
      "scriptId":"u39"},
    "6e8ed8c3e2b4463f8162f3fc9e0d9f15":{
      "scriptId":"u40"},
    "04620a106fa946df9e8c9b7b92737199":{
      "scriptId":"u41"},
    "55ae80b4bca74548bc3e51a1adadb14d":{
      "scriptId":"u42"},
    "92f9517cbecf45baa0b8626d0da52491":{
      "scriptId":"u43"},
    "291a3c16004e40ff99c0d1639e304bab":{
      "scriptId":"u44"},
    "d6e2d12253634fce82405a2b8d4ac5dd":{
      "scriptId":"u45"},
    "39ea5cc0570c418a9e7c85ca02e988c1":{
      "scriptId":"u46"},
    "71263e01155d490ab5d653d50b1b7e60":{
      "scriptId":"u47"},
    "b9dd47f6d4a1468e81b52a8e4870fea2":{
      "scriptId":"u48"},
    "ccb36435cf17475795e615d8d5f89e2b":{
      "scriptId":"u49"},
    "63f05325f53e478087f3b367baad57e7":{
      "scriptId":"u50"},
    "6e4b0874521f42429d1154291d7140a8":{
      "scriptId":"u51"},
    "0a3d23bc13d64786ac07823a55cdf9b3":{
      "scriptId":"u52"},
    "4bd5629e50d04b24b1f8b8cca067a282":{
      "scriptId":"u53"},
    "7ff0dbd5ef35486c966174965c7419fc":{
      "scriptId":"u54"},
    "29cee2be13f44a14a15f535be762463f":{
      "scriptId":"u55"},
    "eae57c748f9840f2be6f488abb54926b":{
      "scriptId":"u56"},
    "9cebeb8ce3db470aa0fe6270a8b9059c":{
      "scriptId":"u57"},
    "67df0752c014481282558e5e5e817cec":{
      "scriptId":"u58"},
    "547c95411e0543f8a37719c693e99b9c":{
      "scriptId":"u59"},
    "8ce85d7f5f1b46ffaf67d9e7deea6cd9":{
      "scriptId":"u60"},
    "f1ac059bce00413780ad08c1e65d401a":{
      "scriptId":"u61"},
    "dce20f96cb2449dda35ca5e6bb73aed1":{
      "scriptId":"u62"},
    "6d700518e1fa4023b1069d29e74db2f7":{
      "scriptId":"u63"},
    "b5040602a3444669b5d94b88a7d217f1":{
      "scriptId":"u64"},
    "505354b157ab43a99ff3369e0aa50bb6":{
      "scriptId":"u65"},
    "843ae8f6057d478995d9fd0f173567e2":{
      "scriptId":"u66"},
    "a0eeeefd72e849538a16b15ab4affd06":{
      "scriptId":"u67"},
    "c20fbe3b063f4649b8852de79a579a14":{
      "scriptId":"u68"},
    "d81364e882c74670af54c6272ee9d37d":{
      "scriptId":"u69"},
    "5c781b63382644ed947e72ceceefdca0":{
      "scriptId":"u70"},
    "9e721779a32d4055b5b11ab9a71729b1":{
      "scriptId":"u71"},
    "41668c9797504b4dbfc82f621b86e1b2":{
      "scriptId":"u72"},
    "c6f19ccacc884e38af7bb53b2c29e4f6":{
      "scriptId":"u73"},
    "a00ee52c140b4e07b0288228b41c6226":{
      "scriptId":"u74"},
    "c0f54691cf8f498f8abe1143d5ed668b":{
      "scriptId":"u75"},
    "577edd15e9934d09ae9323dfb31d2eed":{
      "scriptId":"u76"},
    "1dda4222800c41b79e6b54b56d3efd11":{
      "scriptId":"u77"},
    "cfb33b783c1f42718d608e55ae1cdc09":{
      "scriptId":"u78"},
    "bb952035d07942f78a12e23456045da6":{
      "scriptId":"u79"},
    "307863558b85437ebb0aa3c140b06e72":{
      "scriptId":"u80"},
    "bcaece7dc2cf4461b46a883da6444fac":{
      "scriptId":"u81"},
    "94f924cfeaba49eda1e76c76b61c5db0":{
      "scriptId":"u82"},
    "e8a1cdb76b3e4b369209fbea21aef3b8":{
      "scriptId":"u83"},
    "10c83360973946ea9de0c25eae4acb86":{
      "scriptId":"u84"}}});