$axure.loadCurrentPage({
  "url":"1_快递服务.html",
  "generationDate":new Date(1499311310466.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bcdf9a1f3f640c8bcd99784b091e85a",
    "type":"Axure:Page",
    "name":"1.快递服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a9189f5c9c940d5b36077ab83551ea7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":140,
              "y":64},
            "size":{
              "width":1351,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55a3b486210f46e6892b6f03f62c7066",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":140,
                  "y":64},
                "size":{
                  "width":1351,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u0.png"}},
{
          "id":"ee20c40b398b46b2b14e7ca60ef4def1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1341,
              "y":79},
            "size":{
              "width":120,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44788b4cbd3c46c18dad8406d4c0898b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1341,
                  "y":79},
                "size":{
                  "width":120,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u2.png"}},
{
          "id":"8c6c2494d9df4cedbbddb273cc888776",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":181,
              "y":93},
            "size":{
              "width":181,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f857283164f4d838f31346085911ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":181,
                  "y":93},
                "size":{
                  "width":181,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df47721de3d34e4e86c5df1eedd5ae4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":395,
              "y":66},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bd0c4463274b4db681c5caae42fe7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":395,
                  "y":66},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"a6ee1cdb4ff44c238c8a6ce9c2f7ebe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":521,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eaf9c180a7d49d39d827174b12c533d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":521,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"62346a2771c0480f97b1150eb603788c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":646,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4695f7c181484195ac652db0930f76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":646,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u6.png"}},
{
          "id":"af465655bfa24c708536a062fd7dbeea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":772,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1c8d97bb63b45d595677134c74fbadd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":772,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"24138f2525784c6bac938c280db0d324",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":898,
              "y":65},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7478370440064c989109260d50ac2a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":898,
                  "y":65},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"24b4769207fd458e992b91eddeacb280",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":140,
              "y":138},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e38682d31c64af6974cb382397dc844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":140,
                  "y":138},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"a5560e6bc9034aa0917e6210c2e329f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":694,
              "y":126},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8fe02d851174d1090b22fd177084902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":694,
                  "y":126},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"3cceba79386e4b859f4124448994e38b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":423,
              "y":146},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5376af230cae41d788227c1bfde9ef03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":423,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"c6a168dc5905455897d1f3f963fcab22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF931700},
            "location":{
              "x":540,
              "y":146},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5a9078051e44b55b4e457417aec342d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF931700},
                "location":{
                  "x":540,
                  "y":146},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u18.png"}},
{
          "id":"da262088773c418482af2a8674275b4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":435,
              "y":298},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0958c0e8a4004a5d80df6be5c0ade031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":435,
                  "y":298},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"b9a2a7c5642f4845a498a12b6f1bffcb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":332},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"8d94f1301a1b465b8a4c2fe8f0299de8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":393},
            "size":{
              "width":375,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"184cd8e01f4c4439bef37b2700f39658",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":393},
                "size":{
                  "width":375,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_快递服务/u27.png"}},
{
          "id":"d73ca29033fc4bc9b5c64396c089dc61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":435,
              "y":298},
            "size":{
              "width":375,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db483ee08f9401ba791161ccd1ae358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":435,
                  "y":298},
                "size":{
                  "width":375,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u97.png"}},
{
          "id":"ba18ea6dfb1c415f90090b65fd5fbc31",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":440,
              "y":315},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601f42ed16544b3eb60abd019844f6ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":315},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f3bf916656d43b6a07ed1cc3424f874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":586,
              "y":322},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2820ca908eb3499c846ceaf7258af9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":586,
                  "y":322},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"804ab135c395454c838ac3c7702f78f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":592,
              "y":501},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be42d3298b5646468a461aa2bbea0b6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":592,
                  "y":501},
                "size":{
                  "width":60,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f178c90b20f243b78d3aa7d865e45b7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":437,
              "y":301},
            "size":{
              "width":373,
              "height":12},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a013efbc92be44078832db8ea2a2089c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":437,
                  "y":301},
                "size":{
                  "width":373,
                  "height":12},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u103.png"}},
{
          "id":"0acca7f982254311badb609c39525c86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":451,
              "y":591},
            "size":{
              "width":349,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e47c481fe7e411288e12c55f847f72d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":451,
                  "y":591},
                "size":{
                  "width":349,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56bafe2746af43efbeb8638fbbda75ea",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":614},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"96bb0834b97e4ceb8223a457e1c88bbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":689,
              "y":642},
            "size":{
              "width":105,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9bba557f6fe401b878d0d50656635a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":689,
                  "y":642},
                "size":{
                  "width":105,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u43.png"}},
{
          "id":"617eceead2de4e9cb56eff7656e051c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":457,
              "y":642},
            "size":{
              "width":105,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"914742096d7745829edd6ff6fc3d7485",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":457,
                  "y":642},
                "size":{
                  "width":105,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u43.png"}},
{
          "id":"19a52f8bebec4315b1da3a6e709774f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":574,
              "y":642},
            "size":{
              "width":105,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b968283fa1441b19dee93676deb4c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":574,
                  "y":642},
                "size":{
                  "width":105,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u43.png"}},
{
          "id":"4c13ffab483745d2ad73768cb7f3cf0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":552,
              "y":789},
            "size":{
              "width":148,
              "height":122}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c00c9e07b7b417b8067daba10d3f9d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":552,
                  "y":789},
                "size":{
                  "width":148,
                  "height":122}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_快递服务/u48.png"}},
{
          "id":"a24fb31d2a444420a59d71ddee9962de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":605,
              "y":921},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d54b41533374e598642ed880c12c462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":605,
                  "y":921},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f0c3d01a1f74a3c9584f62736a8cf82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":350},
            "size":{
              "width":375,
              "height":43},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1960b8b9768c46ce9997bf812ab6f58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435,
                  "y":350},
                "size":{
                  "width":375,
                  "height":43},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_快递服务/u52.png"}},
{
          "id":"135b305441bf451c87e1d1706d6f9d94",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":363},
            "size":{
              "width":22,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心-全部功能-地址簿/u131_line.png"}},
{
          "id":"f58c4abbeb694e14ace390734b4583f0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":373},
            "size":{
              "width":22,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心-全部功能-地址簿/u131_line.png"}},
{
          "id":"cdb6030dcaf742ed926c135451a3b0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":448,
              "y":319},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0588da28625746d1af1e9d8ffce934f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":448,
                  "y":319},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8fa5b54595c487cb30998c492b1b935",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":463,
              "y":324},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54749cad66b243a08e4a6b67bcf98031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":463,
                  "y":324},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28abb859e14147c4acb7aa449377dd6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":592,
              "y":365},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"155413b3981c4b938e9ef21d3749b9ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":592,
                  "y":365},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56377507d7b340518569df7f90691fa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":451,
              "y":562},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99ad62d27fb04e96856e83610c69b1a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":451,
                  "y":562},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8a9189f5c9c940d5b36077ab83551ea7":{
      "scriptId":"u0"},
    "55a3b486210f46e6892b6f03f62c7066":{
      "scriptId":"u1"},
    "ee20c40b398b46b2b14e7ca60ef4def1":{
      "scriptId":"u2"},
    "44788b4cbd3c46c18dad8406d4c0898b":{
      "scriptId":"u3"},
    "8c6c2494d9df4cedbbddb273cc888776":{
      "scriptId":"u4"},
    "0f857283164f4d838f31346085911ba1":{
      "scriptId":"u5"},
    "df47721de3d34e4e86c5df1eedd5ae4e":{
      "scriptId":"u6"},
    "31bd0c4463274b4db681c5caae42fe7a":{
      "scriptId":"u7"},
    "a6ee1cdb4ff44c238c8a6ce9c2f7ebe9":{
      "scriptId":"u8"},
    "8eaf9c180a7d49d39d827174b12c533d":{
      "scriptId":"u9"},
    "62346a2771c0480f97b1150eb603788c":{
      "scriptId":"u10"},
    "2a4695f7c181484195ac652db0930f76":{
      "scriptId":"u11"},
    "af465655bfa24c708536a062fd7dbeea":{
      "scriptId":"u12"},
    "e1c8d97bb63b45d595677134c74fbadd":{
      "scriptId":"u13"},
    "24138f2525784c6bac938c280db0d324":{
      "scriptId":"u14"},
    "7478370440064c989109260d50ac2a95":{
      "scriptId":"u15"},
    "24b4769207fd458e992b91eddeacb280":{
      "scriptId":"u16"},
    "4e38682d31c64af6974cb382397dc844":{
      "scriptId":"u17"},
    "a5560e6bc9034aa0917e6210c2e329f3":{
      "scriptId":"u18"},
    "d8fe02d851174d1090b22fd177084902":{
      "scriptId":"u19"},
    "3cceba79386e4b859f4124448994e38b":{
      "scriptId":"u20"},
    "5376af230cae41d788227c1bfde9ef03":{
      "scriptId":"u21"},
    "c6a168dc5905455897d1f3f963fcab22":{
      "scriptId":"u22"},
    "c5a9078051e44b55b4e457417aec342d":{
      "scriptId":"u23"},
    "da262088773c418482af2a8674275b4a":{
      "scriptId":"u24"},
    "0958c0e8a4004a5d80df6be5c0ade031":{
      "scriptId":"u25"},
    "b9a2a7c5642f4845a498a12b6f1bffcb":{
      "scriptId":"u26"},
    "8d94f1301a1b465b8a4c2fe8f0299de8":{
      "scriptId":"u27"},
    "184cd8e01f4c4439bef37b2700f39658":{
      "scriptId":"u28"},
    "d73ca29033fc4bc9b5c64396c089dc61":{
      "scriptId":"u29"},
    "2db483ee08f9401ba791161ccd1ae358":{
      "scriptId":"u30"},
    "ba18ea6dfb1c415f90090b65fd5fbc31":{
      "scriptId":"u31"},
    "601f42ed16544b3eb60abd019844f6ed":{
      "scriptId":"u32"},
    "6f3bf916656d43b6a07ed1cc3424f874":{
      "scriptId":"u33"},
    "2820ca908eb3499c846ceaf7258af9dd":{
      "scriptId":"u34"},
    "804ab135c395454c838ac3c7702f78f3":{
      "scriptId":"u35"},
    "be42d3298b5646468a461aa2bbea0b6d":{
      "scriptId":"u36"},
    "f178c90b20f243b78d3aa7d865e45b7f":{
      "scriptId":"u37"},
    "a013efbc92be44078832db8ea2a2089c":{
      "scriptId":"u38"},
    "0acca7f982254311badb609c39525c86":{
      "scriptId":"u39"},
    "7e47c481fe7e411288e12c55f847f72d":{
      "scriptId":"u40"},
    "56bafe2746af43efbeb8638fbbda75ea":{
      "scriptId":"u41"},
    "96bb0834b97e4ceb8223a457e1c88bbd":{
      "scriptId":"u42"},
    "a9bba557f6fe401b878d0d50656635a1":{
      "scriptId":"u43"},
    "617eceead2de4e9cb56eff7656e051c4":{
      "scriptId":"u44"},
    "914742096d7745829edd6ff6fc3d7485":{
      "scriptId":"u45"},
    "19a52f8bebec4315b1da3a6e709774f5":{
      "scriptId":"u46"},
    "5b968283fa1441b19dee93676deb4c11":{
      "scriptId":"u47"},
    "4c13ffab483745d2ad73768cb7f3cf0f":{
      "scriptId":"u48"},
    "2c00c9e07b7b417b8067daba10d3f9d6":{
      "scriptId":"u49"},
    "a24fb31d2a444420a59d71ddee9962de":{
      "scriptId":"u50"},
    "4d54b41533374e598642ed880c12c462":{
      "scriptId":"u51"},
    "5f0c3d01a1f74a3c9584f62736a8cf82":{
      "scriptId":"u52"},
    "1960b8b9768c46ce9997bf812ab6f58d":{
      "scriptId":"u53"},
    "135b305441bf451c87e1d1706d6f9d94":{
      "scriptId":"u54"},
    "f58c4abbeb694e14ace390734b4583f0":{
      "scriptId":"u55"},
    "cdb6030dcaf742ed926c135451a3b0db":{
      "scriptId":"u56"},
    "0588da28625746d1af1e9d8ffce934f1":{
      "scriptId":"u57"},
    "f8fa5b54595c487cb30998c492b1b935":{
      "scriptId":"u58"},
    "54749cad66b243a08e4a6b67bcf98031":{
      "scriptId":"u59"},
    "28abb859e14147c4acb7aa449377dd6c":{
      "scriptId":"u60"},
    "155413b3981c4b938e9ef21d3749b9ae":{
      "scriptId":"u61"},
    "56377507d7b340518569df7f90691fa0":{
      "scriptId":"u62"},
    "99ad62d27fb04e96856e83610c69b1a4":{
      "scriptId":"u63"}}});