$axure.loadCurrentPage({
  "url":"个人中心-全部功能-快递服务.html",
  "generationDate":new Date(1499311304882.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b51280ed9cc40a7acc52f81bc2a8ecb",
    "type":"Axure:Page",
    "name":"个人中心-全部功能-快递服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f15b77349eb24ee299f654cd0a1edaf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":9,
              "y":70},
            "size":{
              "width":1351,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6469c6adfc9c4dadb794222bf036f944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":9,
                  "y":70},
                "size":{
                  "width":1351,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u0.png"}},
{
          "id":"c9dacb5f076d425983fd0f55a6d0b2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1210,
              "y":85},
            "size":{
              "width":120,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df26fef057bf47b680ccda797d7e4d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1210,
                  "y":85},
                "size":{
                  "width":120,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u2.png"}},
{
          "id":"458827e54dff4047a89ae523ec023507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":50,
              "y":99},
            "size":{
              "width":181,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59dccb57343d4453ba5fdfa2aeaa7900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":99},
                "size":{
                  "width":181,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a628a42d13347bc8d9db8e6a01cf6dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":264,
              "y":72},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eae0afa9d1454f41a6dd36baf0be35a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":264,
                  "y":72},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"e96001be79334d468b72151579415026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":390,
              "y":71},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7170cad42264235ba769d721ed6a60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":390,
                  "y":71},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"6ae86f673f994579a83d380e1c552954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":515,
              "y":71},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67d7ecac73145a3a7d632c214503aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":515,
                  "y":71},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u6.png"}},
{
          "id":"b9d547fe1d654ba0b77da53ebbcc4e7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":641,
              "y":71},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b7ea715515430f8050bccbcb90246e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":641,
                  "y":71},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"6e77dc7282ab4825881e287fcc0801fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":767,
              "y":71},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4028353f6504419f9ae4c14eac912557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":767,
                  "y":71},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"f94ba62035194f8cbe7415c9279e01c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":9,
              "y":144},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04d05918270b4184b98131394381f8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":9,
                  "y":144},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"7c4f9a5d3cb141eaa42fea9ba9e3c040",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":563,
              "y":132},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7268626959d54a22bfb3d4507ca60181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":563,
                  "y":132},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"a85433b9ec8e4f3f85f1cb60be8b8452",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":292,
              "y":152},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1413ed82c7c3408ea82dc862ec5c1006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":292,
                  "y":152},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"5860b51c86f74f9894169f38360cfbbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF931700},
            "location":{
              "x":409,
              "y":152},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f34d860a78d4ca083a9253ce4ed1558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF931700},
                "location":{
                  "x":409,
                  "y":152},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u18.png"}},
{
          "id":"475da1487a8f47d1ab8e1f2dc858cffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":304,
              "y":304},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950cb38bc84f48f780e9d1c923c7955c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":304,
                  "y":304},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u93.png"}},
{
          "id":"4d0cd436e0474125ae790e2d2d498f9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":338},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"82b3b95ec7f846fda4f0fbf53568c738",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":304,
              "y":304},
            "size":{
              "width":375,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7d40f4b073546909440b280b03d93ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":304,
                  "y":304},
                "size":{
                  "width":375,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u97.png"}},
{
          "id":"88eca8b634e8433791631566a523bf05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":309,
              "y":321},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49bbfdaa50d143a3a2e9a7de065fb440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":309,
                  "y":321},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"488777359ac74165874b89060e8a1145",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":455,
              "y":331},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71c0a47ff9a42c4aed09ee9b93baa60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":455,
                  "y":331},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d53663a688942c3b86ab8404a775920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":465,
              "y":466},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b818045aa7544d12b98509203d08f800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":465,
                  "y":466},
                "size":{
                  "width":60,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeaf4f9e418a424e8849ce29f8e6dda5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":306,
              "y":307},
            "size":{
              "width":373,
              "height":12},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d68cf6068f8494abdfff78f74182cd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":307},
                "size":{
                  "width":373,
                  "height":12},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u103.png"}},
{
          "id":"3c931b0fbc6541aba74a0512c6f0bde7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":319,
              "y":326},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5285337e9b4746258fe4afd85aeae17c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":319,
                  "y":326},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c27fedccbc44e084b558ca2c539a28",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":500},
            "size":{
              "width":373,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心-全部功能-抽屉/u39_line.png"}},
{
          "id":"4b62a99840374008a2e30fe95f3eaf3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":526},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bd335ccb51d4add89234347a9b077c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":526},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d71fa812b83d435da06502bb025d3f0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":304,
              "y":356},
            "size":{
              "width":256,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ac2a5cdf9f42f49999f71240815977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":304,
                  "y":356},
                "size":{
                  "width":256,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-全部功能-抽屉/u42.png"}},
{
          "id":"2129b0e731134548a6ce3bb8e77cf26e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":459},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3c440dfb810463f8906970a098b0a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":459},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2113109cba0c4150b1865d61dd87af37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":396},
            "size":{
              "width":53,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa5e5d1e10f1428d9ef6dc80bc7153d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":396},
                "size":{
                  "width":53,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-全部功能-抽屉/u70.png"}},
{
          "id":"9c8ab4c6e4524256b674e7f5d250a7a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":304,
              "y":505},
            "size":{
              "width":255,
              "height":466}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b389977eddb41c191fadc71675d035a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":304,
                  "y":505},
                "size":{
                  "width":255,
                  "height":466}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-全部功能-抽屉/u44.png"}},
{
          "id":"e941109416fc459883874c0b6887cb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":526},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfac796fcaf54c1caea3eea59dee4479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":526},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3999bcb130041da9aa3981d0703c60a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":520},
            "size":{
              "width":26,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e050f57414eb4a52a85da81606c14aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":520},
                "size":{
                  "width":26,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-全部功能-抽屉/u56.png"}},
{
          "id":"4b18435ed8ed4363ba2f421413a8d207",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":395,
              "y":562},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"287faf0e4e8544dabd3517f94e3fee61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":562},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e76913d3e68042fb8967d3975adb4e9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":378,
              "y":558},
            "size":{
              "width":25,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b07ce1464594d1c999f31e46e6a8b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":378,
                  "y":558},
                "size":{
                  "width":25,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc16bda9ca304c47b23293441988729e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":395,
              "y":598},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df08af6bf86f49e0b8eabd49b2e58bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":598},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79630fb651394a2aa20bbc9174b2d76f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":378,
              "y":594},
            "size":{
              "width":25,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d99b53958ab44679d07c65f0a49b502",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":378,
                  "y":594},
                "size":{
                  "width":25,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2985215ccaad448a86301740a6de173f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":395,
              "y":632},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cdc7b8c280545c7bbc0413614502968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":395,
                  "y":632},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"780eec3729c84e639203c8c001ffe949",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":378,
              "y":628},
            "size":{
              "width":25,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068a3584ef294a9e97dc87617a2089b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":378,
                  "y":628},
                "size":{
                  "width":25,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7d02291b2cf4ffa866bbbe0d4edcd83",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":529},
            "size":{
              "width":18,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心-全部功能-快递服务/u66_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f15b77349eb24ee299f654cd0a1edaf2":{
      "scriptId":"u0"},
    "6469c6adfc9c4dadb794222bf036f944":{
      "scriptId":"u1"},
    "c9dacb5f076d425983fd0f55a6d0b2b3":{
      "scriptId":"u2"},
    "df26fef057bf47b680ccda797d7e4d2e":{
      "scriptId":"u3"},
    "458827e54dff4047a89ae523ec023507":{
      "scriptId":"u4"},
    "59dccb57343d4453ba5fdfa2aeaa7900":{
      "scriptId":"u5"},
    "8a628a42d13347bc8d9db8e6a01cf6dc":{
      "scriptId":"u6"},
    "eae0afa9d1454f41a6dd36baf0be35a2":{
      "scriptId":"u7"},
    "e96001be79334d468b72151579415026":{
      "scriptId":"u8"},
    "f7170cad42264235ba769d721ed6a60e":{
      "scriptId":"u9"},
    "6ae86f673f994579a83d380e1c552954":{
      "scriptId":"u10"},
    "e67d7ecac73145a3a7d632c214503aaa":{
      "scriptId":"u11"},
    "b9d547fe1d654ba0b77da53ebbcc4e7e":{
      "scriptId":"u12"},
    "98b7ea715515430f8050bccbcb90246e":{
      "scriptId":"u13"},
    "6e77dc7282ab4825881e287fcc0801fb":{
      "scriptId":"u14"},
    "4028353f6504419f9ae4c14eac912557":{
      "scriptId":"u15"},
    "f94ba62035194f8cbe7415c9279e01c1":{
      "scriptId":"u16"},
    "04d05918270b4184b98131394381f8f0":{
      "scriptId":"u17"},
    "7c4f9a5d3cb141eaa42fea9ba9e3c040":{
      "scriptId":"u18"},
    "7268626959d54a22bfb3d4507ca60181":{
      "scriptId":"u19"},
    "a85433b9ec8e4f3f85f1cb60be8b8452":{
      "scriptId":"u20"},
    "1413ed82c7c3408ea82dc862ec5c1006":{
      "scriptId":"u21"},
    "5860b51c86f74f9894169f38360cfbbb":{
      "scriptId":"u22"},
    "8f34d860a78d4ca083a9253ce4ed1558":{
      "scriptId":"u23"},
    "475da1487a8f47d1ab8e1f2dc858cffd":{
      "scriptId":"u24"},
    "950cb38bc84f48f780e9d1c923c7955c":{
      "scriptId":"u25"},
    "4d0cd436e0474125ae790e2d2d498f9b":{
      "scriptId":"u26"},
    "82b3b95ec7f846fda4f0fbf53568c738":{
      "scriptId":"u27"},
    "f7d40f4b073546909440b280b03d93ae":{
      "scriptId":"u28"},
    "88eca8b634e8433791631566a523bf05":{
      "scriptId":"u29"},
    "49bbfdaa50d143a3a2e9a7de065fb440":{
      "scriptId":"u30"},
    "488777359ac74165874b89060e8a1145":{
      "scriptId":"u31"},
    "c71c0a47ff9a42c4aed09ee9b93baa60":{
      "scriptId":"u32"},
    "0d53663a688942c3b86ab8404a775920":{
      "scriptId":"u33"},
    "b818045aa7544d12b98509203d08f800":{
      "scriptId":"u34"},
    "aeaf4f9e418a424e8849ce29f8e6dda5":{
      "scriptId":"u35"},
    "9d68cf6068f8494abdfff78f74182cd4":{
      "scriptId":"u36"},
    "3c931b0fbc6541aba74a0512c6f0bde7":{
      "scriptId":"u37"},
    "5285337e9b4746258fe4afd85aeae17c":{
      "scriptId":"u38"},
    "95c27fedccbc44e084b558ca2c539a28":{
      "scriptId":"u39"},
    "4b62a99840374008a2e30fe95f3eaf3c":{
      "scriptId":"u40"},
    "2bd335ccb51d4add89234347a9b077c4":{
      "scriptId":"u41"},
    "d71fa812b83d435da06502bb025d3f0d":{
      "scriptId":"u42"},
    "b8ac2a5cdf9f42f49999f71240815977":{
      "scriptId":"u43"},
    "2129b0e731134548a6ce3bb8e77cf26e":{
      "scriptId":"u44"},
    "b3c440dfb810463f8906970a098b0a47":{
      "scriptId":"u45"},
    "2113109cba0c4150b1865d61dd87af37":{
      "scriptId":"u46"},
    "aa5e5d1e10f1428d9ef6dc80bc7153d4":{
      "scriptId":"u47"},
    "9c8ab4c6e4524256b674e7f5d250a7a3":{
      "scriptId":"u48"},
    "2b389977eddb41c191fadc71675d035a":{
      "scriptId":"u49"},
    "e941109416fc459883874c0b6887cb0f":{
      "scriptId":"u50"},
    "dfac796fcaf54c1caea3eea59dee4479":{
      "scriptId":"u51"},
    "f3999bcb130041da9aa3981d0703c60a":{
      "scriptId":"u52"},
    "e050f57414eb4a52a85da81606c14aa7":{
      "scriptId":"u53"},
    "4b18435ed8ed4363ba2f421413a8d207":{
      "scriptId":"u54"},
    "287faf0e4e8544dabd3517f94e3fee61":{
      "scriptId":"u55"},
    "e76913d3e68042fb8967d3975adb4e9e":{
      "scriptId":"u56"},
    "9b07ce1464594d1c999f31e46e6a8b44":{
      "scriptId":"u57"},
    "dc16bda9ca304c47b23293441988729e":{
      "scriptId":"u58"},
    "df08af6bf86f49e0b8eabd49b2e58bf6":{
      "scriptId":"u59"},
    "79630fb651394a2aa20bbc9174b2d76f":{
      "scriptId":"u60"},
    "1d99b53958ab44679d07c65f0a49b502":{
      "scriptId":"u61"},
    "2985215ccaad448a86301740a6de173f":{
      "scriptId":"u62"},
    "9cdc7b8c280545c7bbc0413614502968":{
      "scriptId":"u63"},
    "780eec3729c84e639203c8c001ffe949":{
      "scriptId":"u64"},
    "068a3584ef294a9e97dc87617a2089b9":{
      "scriptId":"u65"},
    "f7d02291b2cf4ffa866bbbe0d4edcd83":{
      "scriptId":"u66"}}});