$axure.loadCurrentPage({
  "url":"全局说明.html",
  "generationDate":new Date(1499311304142.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"57e7e79b34574bd8bdc19a375c6e5d00",
    "type":"Axure:Page",
    "name":"全局说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0f712813783e4027b847e33464bc11a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":-1,
              "y":0},
            "size":{
              "width":1351,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5242a8dc208d4c7da2e86e8e2bc6aba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":-1,
                  "y":0},
                "size":{
                  "width":1351,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u0.png"}},
{
          "id":"3bed84040e754483988ab7331e2fa1da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1200,
              "y":15},
            "size":{
              "width":120,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d3cb4be171444bbb46710241342984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1200,
                  "y":15},
                "size":{
                  "width":120,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u2.png"}},
{
          "id":"135b97ee7fdf4f49a4e560c3113b7dc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":40,
              "y":29},
            "size":{
              "width":145,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0702ec4bcaa45908ad3b014a0b76540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":29},
                "size":{
                  "width":145,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f59ef9084ae4561a40d7c8a6cd94039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":254,
              "y":2},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5519c5f5990c4d98bd6eef0206fd44de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":254,
                  "y":2},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"70a8c54beba24f54bf2f2ad4f4fb0ebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":380,
              "y":1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03ad6a2390754f5b87580346de9c5647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":380,
                  "y":1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"e0ac990ac4764f0dbe01beac9139b364",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":505,
              "y":1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b8f59bcf2d942bc8b73b22e24dfa428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":505,
                  "y":1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u6.png"}},
{
          "id":"27f869776268439fab96f767ea2b221f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":631,
              "y":1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace1753fe2464fca92a3e0321b54d4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":631,
                  "y":1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"a7e7dac9167d4ebf84c18f0618db5b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF1A1A1A},
            "location":{
              "x":757,
              "y":1},
            "size":{
              "width":126,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0f1fb221e44d2b9f8f485ea0c7c78b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF1A1A1A},
                "location":{
                  "x":757,
                  "y":1},
                "size":{
                  "width":126,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u8.png"}},
{
          "id":"3f148eab20494f5e8b99c12e35d8e7a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":-1,
              "y":74},
            "size":{
              "width":1351,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b427ad3775ca4007999fc8a9de12892a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":-1,
                  "y":74},
                "size":{
                  "width":1351,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u14.png"}},
{
          "id":"063546907a5044afaca49b0790d6de68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":553,
              "y":62},
            "size":{
              "width":37,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638601ddbbc74021820a56cdb0efce45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":553,
                  "y":62},
                "size":{
                  "width":37,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品介绍/u16.png"}},
{
          "id":"96ffaadfca7e4062b162fde7a96940c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF931700},
            "location":{
              "x":282,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9e85e6fdfa24b8aa2ba8f94f858ae21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF931700},
                "location":{
                  "x":282,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u18.png"}},
{
          "id":"aa4427819ef742fa8e8b4860a767f215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF62E00},
            "location":{
              "x":399,
              "y":82},
            "size":{
              "width":90,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5859f748d86947298b6b44f18a6cbfb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF62E00},
                "location":{
                  "x":399,
                  "y":82},
                "size":{
                  "width":90,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/产品介绍/u20.png"}},
{
          "id":"f42745c330634f7592a3f5292283be13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":540,
              "y":160},
            "size":{
              "width":210,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b8385b6c2394aeea4773c0822e19b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Microsoft YaHei Regular', 'Microsoft YaHei'",
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "location":{
                  "x":540,
                  "y":160},
                "size":{
                  "width":210,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3335cb87b43f4fc689ceba7d08f21952",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":140,
              "y":252},
            "size":{
              "width":720,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9845f1f99d5c4c8e9e5877991dd9fe9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":140,
                  "y":252},
                "size":{
                  "width":720,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ec7ddf65a37470da9ca05c1dbae67ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":293},
            "size":{
              "width":292,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bc62850962846099853b5b367fcd355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":293},
                "size":{
                  "width":292,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8347f8798eaf45d296e39ab0ebd04040",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":333},
            "size":{
              "width":116,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42ca630bd3a48b4be64a4012b9c35a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":333},
                "size":{
                  "width":116,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"849671d7af174031b385a4a146d965e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":363},
            "size":{
              "width":64,
              "height":64},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.749019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc76f3d8a86488b9f2a08de22b0188a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":363},
                "size":{
                  "width":64,
                  "height":64},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.749019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u32.png"}},
{
          "id":"ffcee38136a14d7f854cc1eb5fbb7d0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":363},
            "size":{
              "width":64,
              "height":64},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.749019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a5c30a0c7d14dc081c1155eb2c52605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":363},
                "size":{
                  "width":64,
                  "height":64},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.749019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u32.png"}},
{
          "id":"0e17a9d7670c431d99203f4d6a025ae2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":376,
              "y":363},
            "size":{
              "width":64,
              "height":64},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":0,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.749019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320ea9d55deb4b8fbc77d38855b3ec16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":376,
                  "y":363},
                "size":{
                  "width":64,
                  "height":64},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":0,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.749019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u36.png"}},
{
          "id":"450bda57a3aa4958a94aaef6a415b5bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":252,
              "y":333},
            "size":{
              "width":116,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef00d6b2d1a47de8ef3a2e6531394d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":252,
                  "y":333},
                "size":{
                  "width":116,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f0c06eb7a504be694c08c2e7a265fb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":384,
              "y":333},
            "size":{
              "width":116,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eca9ea8cde424dc6b4d6a8c69ffd5620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":384,
                  "y":333},
                "size":{
                  "width":116,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1dc6be8fc0748e5ab2e27393594b7a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":491},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0b5a2b99d5641a4b2338b17171fcccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":491},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c6db99d65714711b20486960b348cbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":451},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea530dae8ca4e71a9610f2b2c1c80ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":451},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db831482614d4fca9441f3de5590e114",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":353,
              "y":491},
            "size":{
              "width":236,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad78da74cebb49108b8273b32c39cc31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":353,
                  "y":491},
                "size":{
                  "width":236,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e60cccc53a6479dae2943d6a72da492",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":651},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e2b4aa0d32492a8b167f107d6105f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":651},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78912968cf8a45ac9f5e85892cfd0d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":581},
            "size":{
              "width":192,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4f4002fd0d476abeab54e8155c7020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":581},
                "size":{
                  "width":192,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d64bf329b01499dba641b3db93bb468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":354,
              "y":581},
            "size":{
              "width":270,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b124d1887cac4d0da6486afadc8d4ec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":354,
                  "y":581},
                "size":{
                  "width":270,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c7b50df119a46bebcdf183b1e884ce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":354,
              "y":651},
            "size":{
              "width":243,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57f16ae15a24a9fadd0e6e396e4febd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":354,
                  "y":651},
                "size":{
                  "width":243,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baecd87ff78a4977a9a4444037f52414",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":541},
            "size":{
              "width":196,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e76a952722f441f1a1e0942a77bea0b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":541},
                "size":{
                  "width":196,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af771a0fd5fd429bb5d59735354a701b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":353,
              "y":541},
            "size":{
              "width":236,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd802cd178d44059a7b99f05c32744ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":353,
                  "y":541},
                "size":{
                  "width":236,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"199bfccc21dd4cb49ab57d9ff020cf51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":789},
            "size":{
              "width":470,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed0f83f89bd04143ae97ffff2ae6270b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":789},
                "size":{
                  "width":470,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6bd21f6fa2947de88c7d80f0bf6cc7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":745},
            "size":{
              "width":116,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd7585e89cc4c51943966b669a24518",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":745},
                "size":{
                  "width":116,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b050cf63d7f4baa879002d61fdee08b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":140,
              "y":890},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b35a8b907ec3454881ad332f342d6a02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":140,
              "y":850},
            "size":{
              "width":116,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1ac712ebc4444c8d32384dcab2a2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":850},
                "size":{
                  "width":116,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4af6d5f590674c68b2badd95d03e45c5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":140,
              "y":970},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c7a3431129d341d4937121f4ce6df5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":454,
              "y":890},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565396443cf34de5aa50f50ab87424ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":454,
                  "y":890},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdf94a2196834669bc128d17907c9af4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":140,
              "y":930},
            "size":{
              "width":300,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"58c890a2d63143d1aedc40f59f90d0f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":454,
              "y":930},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b857e812345b4623b26ca2a1f2c44e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":454,
                  "y":930},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d32dad9f13bb408694b79052cb69b5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":454,
              "y":970},
            "size":{
              "width":98,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9b42cef8184f6b94adaf67bb801f13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":454,
                  "y":970},
                "size":{
                  "width":98,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a073c6c2f9e64f3d9685dc3350dbdb0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":140,
              "y":1087},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef34995c9f06473ea98f08cb005aa634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":140,
                  "y":1087},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u75.png"}},
{
          "id":"d8e429a92c794cddaf8c463517b0e1d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":188,
              "y":1320},
            "size":{
              "width":280,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0091487e5e25434fbb02ad1aa2e2544c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":188,
                  "y":1320},
                "size":{
                  "width":280,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u77.png"}},
{
          "id":"e4f344bcd06e46d295d0a0ede8b6d613",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "location":{
              "x":140,
              "y":1030},
            "size":{
              "width":500,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6501b8c376d2460fa4b2f6997d741471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "location":{
                  "x":140,
                  "y":1030},
                "size":{
                  "width":500,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba5a654802664d29b199fdae6a1c9c88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":540,
              "y":1170},
            "size":{
              "width":280,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b3d77081134fad9fec65cd9366e2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":540,
                  "y":1170},
                "size":{
                  "width":280,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u81.png"}},
{
          "id":"86098a30a67c4d27a1fb15d19673d5ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":560,
              "y":1194},
            "size":{
              "width":240,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672f2baa94c1483cacca9322ed4c59dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":560,
                  "y":1194},
                "size":{
                  "width":240,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"106745dbf5e748bb8ca93b8a5f4177d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":540,
              "y":1260},
            "size":{
              "width":140,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8892d194f834915baf6880bb6e96c94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":540,
                  "y":1260},
                "size":{
                  "width":140,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u85.png"}},
{
          "id":"01aad5e8d83f414a9964bc530d7e9993",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":680,
              "y":1260},
            "size":{
              "width":140,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"939e427a1fa649499f157ee5a0d37100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":680,
                  "y":1260},
                "size":{
                  "width":140,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u87.png"}},
{
          "id":"eb31ee5d4c95473f8772d9bb94764a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":140,
              "y":1803},
            "size":{
              "width":500,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ada2699edd524315997a1b22081f9929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":140,
                  "y":1803},
                "size":{
                  "width":500,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1becb45fbb3434b8f016bd7be0c8cc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":140,
              "y":1860},
            "size":{
              "width":320,
              "height":15},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8dc9522b3ab4bddbff4a4b2299b7c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":140,
                  "y":1860},
                "size":{
                  "width":320,
                  "height":15},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u91.png"}},
{
          "id":"b380ca24463a40f499a9a18226f32109",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "location":{
              "x":140,
              "y":1860},
            "size":{
              "width":375,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0f5a90fc67647c6aebd6b309ce24f66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "location":{
                  "x":140,
                  "y":1860},
                "size":{
                  "width":375,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u93.png"}},
{
          "id":"19fa0e272f664ff9af7960c64def5c8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":200,
              "y":1867},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"923d91b9a88943d9a597019aefc34ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":200,
                  "y":1867},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"126074f56e8f41d09295545574f3835f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":140,
              "y":1860},
            "size":{
              "width":375,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777f24872708476dad0621867f8ef01c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":140,
                  "y":1860},
                "size":{
                  "width":375,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u97.png"}},
{
          "id":"a906c017cdd44dcc8797396f7c064954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":146,
              "y":1877},
            "size":{
              "width":60,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177abd8c318141f1b509f30497646e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":146,
                  "y":1877},
                "size":{
                  "width":60,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45ed20a0f168471e9d9a95f50ab965fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":292,
              "y":1884},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f737699b0d5c416c9672ec65fed108e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":1884},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d132d9a2110e44ddbdbe9cdc6af2307d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":142,
              "y":1863},
            "size":{
              "width":373,
              "height":12},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08a26b254bb946f7ba38c058aa6fd599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":1863},
                "size":{
                  "width":373,
                  "height":12},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全局说明/u103.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0f712813783e4027b847e33464bc11a1":{
      "scriptId":"u0"},
    "5242a8dc208d4c7da2e86e8e2bc6aba3":{
      "scriptId":"u1"},
    "3bed84040e754483988ab7331e2fa1da":{
      "scriptId":"u2"},
    "e7d3cb4be171444bbb46710241342984":{
      "scriptId":"u3"},
    "135b97ee7fdf4f49a4e560c3113b7dc5":{
      "scriptId":"u4"},
    "e0702ec4bcaa45908ad3b014a0b76540":{
      "scriptId":"u5"},
    "1f59ef9084ae4561a40d7c8a6cd94039":{
      "scriptId":"u6"},
    "5519c5f5990c4d98bd6eef0206fd44de":{
      "scriptId":"u7"},
    "70a8c54beba24f54bf2f2ad4f4fb0ebd":{
      "scriptId":"u8"},
    "03ad6a2390754f5b87580346de9c5647":{
      "scriptId":"u9"},
    "e0ac990ac4764f0dbe01beac9139b364":{
      "scriptId":"u10"},
    "5b8f59bcf2d942bc8b73b22e24dfa428":{
      "scriptId":"u11"},
    "27f869776268439fab96f767ea2b221f":{
      "scriptId":"u12"},
    "ace1753fe2464fca92a3e0321b54d4a2":{
      "scriptId":"u13"},
    "a7e7dac9167d4ebf84c18f0618db5b2c":{
      "scriptId":"u14"},
    "bb0f1fb221e44d2b9f8f485ea0c7c78b":{
      "scriptId":"u15"},
    "3f148eab20494f5e8b99c12e35d8e7a7":{
      "scriptId":"u16"},
    "b427ad3775ca4007999fc8a9de12892a":{
      "scriptId":"u17"},
    "063546907a5044afaca49b0790d6de68":{
      "scriptId":"u18"},
    "638601ddbbc74021820a56cdb0efce45":{
      "scriptId":"u19"},
    "96ffaadfca7e4062b162fde7a96940c8":{
      "scriptId":"u20"},
    "e9e85e6fdfa24b8aa2ba8f94f858ae21":{
      "scriptId":"u21"},
    "aa4427819ef742fa8e8b4860a767f215":{
      "scriptId":"u22"},
    "5859f748d86947298b6b44f18a6cbfb8":{
      "scriptId":"u23"},
    "f42745c330634f7592a3f5292283be13":{
      "scriptId":"u24"},
    "4b8385b6c2394aeea4773c0822e19b81":{
      "scriptId":"u25"},
    "3335cb87b43f4fc689ceba7d08f21952":{
      "scriptId":"u26"},
    "9845f1f99d5c4c8e9e5877991dd9fe9c":{
      "scriptId":"u27"},
    "6ec7ddf65a37470da9ca05c1dbae67ca":{
      "scriptId":"u28"},
    "8bc62850962846099853b5b367fcd355":{
      "scriptId":"u29"},
    "8347f8798eaf45d296e39ab0ebd04040":{
      "scriptId":"u30"},
    "e42ca630bd3a48b4be64a4012b9c35a8":{
      "scriptId":"u31"},
    "849671d7af174031b385a4a146d965e9":{
      "scriptId":"u32"},
    "4cc76f3d8a86488b9f2a08de22b0188a":{
      "scriptId":"u33"},
    "ffcee38136a14d7f854cc1eb5fbb7d0d":{
      "scriptId":"u34"},
    "8a5c30a0c7d14dc081c1155eb2c52605":{
      "scriptId":"u35"},
    "0e17a9d7670c431d99203f4d6a025ae2":{
      "scriptId":"u36"},
    "320ea9d55deb4b8fbc77d38855b3ec16":{
      "scriptId":"u37"},
    "450bda57a3aa4958a94aaef6a415b5bf":{
      "scriptId":"u38"},
    "aef00d6b2d1a47de8ef3a2e6531394d3":{
      "scriptId":"u39"},
    "2f0c06eb7a504be694c08c2e7a265fb3":{
      "scriptId":"u40"},
    "eca9ea8cde424dc6b4d6a8c69ffd5620":{
      "scriptId":"u41"},
    "a1dc6be8fc0748e5ab2e27393594b7a0":{
      "scriptId":"u42"},
    "f0b5a2b99d5641a4b2338b17171fcccb":{
      "scriptId":"u43"},
    "1c6db99d65714711b20486960b348cbc":{
      "scriptId":"u44"},
    "7ea530dae8ca4e71a9610f2b2c1c80ae":{
      "scriptId":"u45"},
    "db831482614d4fca9441f3de5590e114":{
      "scriptId":"u46"},
    "ad78da74cebb49108b8273b32c39cc31":{
      "scriptId":"u47"},
    "1e60cccc53a6479dae2943d6a72da492":{
      "scriptId":"u48"},
    "d1e2b4aa0d32492a8b167f107d6105f1":{
      "scriptId":"u49"},
    "78912968cf8a45ac9f5e85892cfd0d13":{
      "scriptId":"u50"},
    "4d4f4002fd0d476abeab54e8155c7020":{
      "scriptId":"u51"},
    "3d64bf329b01499dba641b3db93bb468":{
      "scriptId":"u52"},
    "b124d1887cac4d0da6486afadc8d4ec4":{
      "scriptId":"u53"},
    "9c7b50df119a46bebcdf183b1e884ce2":{
      "scriptId":"u54"},
    "b57f16ae15a24a9fadd0e6e396e4febd":{
      "scriptId":"u55"},
    "baecd87ff78a4977a9a4444037f52414":{
      "scriptId":"u56"},
    "e76a952722f441f1a1e0942a77bea0b5":{
      "scriptId":"u57"},
    "af771a0fd5fd429bb5d59735354a701b":{
      "scriptId":"u58"},
    "fd802cd178d44059a7b99f05c32744ed":{
      "scriptId":"u59"},
    "199bfccc21dd4cb49ab57d9ff020cf51":{
      "scriptId":"u60"},
    "ed0f83f89bd04143ae97ffff2ae6270b":{
      "scriptId":"u61"},
    "b6bd21f6fa2947de88c7d80f0bf6cc7c":{
      "scriptId":"u62"},
    "ddd7585e89cc4c51943966b669a24518":{
      "scriptId":"u63"},
    "6b050cf63d7f4baa879002d61fdee08b":{
      "scriptId":"u64"},
    "b35a8b907ec3454881ad332f342d6a02":{
      "scriptId":"u65"},
    "2d1ac712ebc4444c8d32384dcab2a2dd":{
      "scriptId":"u66"},
    "4af6d5f590674c68b2badd95d03e45c5":{
      "scriptId":"u67"},
    "c7a3431129d341d4937121f4ce6df5a3":{
      "scriptId":"u68"},
    "565396443cf34de5aa50f50ab87424ac":{
      "scriptId":"u69"},
    "fdf94a2196834669bc128d17907c9af4":{
      "scriptId":"u70"},
    "58c890a2d63143d1aedc40f59f90d0f3":{
      "scriptId":"u71"},
    "b857e812345b4623b26ca2a1f2c44e6e":{
      "scriptId":"u72"},
    "d32dad9f13bb408694b79052cb69b5a3":{
      "scriptId":"u73"},
    "0b9b42cef8184f6b94adaf67bb801f13":{
      "scriptId":"u74"},
    "a073c6c2f9e64f3d9685dc3350dbdb0a":{
      "scriptId":"u75"},
    "ef34995c9f06473ea98f08cb005aa634":{
      "scriptId":"u76"},
    "d8e429a92c794cddaf8c463517b0e1d9":{
      "scriptId":"u77"},
    "0091487e5e25434fbb02ad1aa2e2544c":{
      "scriptId":"u78"},
    "e4f344bcd06e46d295d0a0ede8b6d613":{
      "scriptId":"u79"},
    "6501b8c376d2460fa4b2f6997d741471":{
      "scriptId":"u80"},
    "ba5a654802664d29b199fdae6a1c9c88":{
      "scriptId":"u81"},
    "c7b3d77081134fad9fec65cd9366e2ae":{
      "scriptId":"u82"},
    "86098a30a67c4d27a1fb15d19673d5ab":{
      "scriptId":"u83"},
    "672f2baa94c1483cacca9322ed4c59dc":{
      "scriptId":"u84"},
    "106745dbf5e748bb8ca93b8a5f4177d8":{
      "scriptId":"u85"},
    "f8892d194f834915baf6880bb6e96c94":{
      "scriptId":"u86"},
    "01aad5e8d83f414a9964bc530d7e9993":{
      "scriptId":"u87"},
    "939e427a1fa649499f157ee5a0d37100":{
      "scriptId":"u88"},
    "eb31ee5d4c95473f8772d9bb94764a9f":{
      "scriptId":"u89"},
    "ada2699edd524315997a1b22081f9929":{
      "scriptId":"u90"},
    "d1becb45fbb3434b8f016bd7be0c8cc6":{
      "scriptId":"u91"},
    "a8dc9522b3ab4bddbff4a4b2299b7c05":{
      "scriptId":"u92"},
    "b380ca24463a40f499a9a18226f32109":{
      "scriptId":"u93"},
    "e0f5a90fc67647c6aebd6b309ce24f66":{
      "scriptId":"u94"},
    "19fa0e272f664ff9af7960c64def5c8c":{
      "scriptId":"u95"},
    "923d91b9a88943d9a597019aefc34ae4":{
      "scriptId":"u96"},
    "126074f56e8f41d09295545574f3835f":{
      "scriptId":"u97"},
    "777f24872708476dad0621867f8ef01c":{
      "scriptId":"u98"},
    "a906c017cdd44dcc8797396f7c064954":{
      "scriptId":"u99"},
    "177abd8c318141f1b509f30497646e2d":{
      "scriptId":"u100"},
    "45ed20a0f168471e9d9a95f50ab965fa":{
      "scriptId":"u101"},
    "f737699b0d5c416c9672ec65fed108e1":{
      "scriptId":"u102"},
    "d132d9a2110e44ddbdbe9cdc6af2307d":{
      "scriptId":"u103"},
    "08a26b254bb946f7ba38c058aa6fd599":{
      "scriptId":"u104"}}});